'use strict';
// Windows package deliberately uses ssh2's portable JS implementation.
require('node:module')._extensions['.node']=()=>{throw new Error('Native addons disabled for portable SSH/SFTP test');};
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const {Server,Transfers,profile,safeDownloadName,name,call,publicError}=require('../src/core.cjs');const {fixture}=require('./fixture.cjs');
test('public Android profile validates and excludes secrets',()=>{const p=profile({format:'localls-server-v1',host:'192.168.1.82',port:8022,user:'u0_a606',folder:'/data/data/com.termux/files/home/LocalLS',password:'example-unused',token:'example-unused'});assert.equal(p.format,'localls-server-v1');assert.equal('password' in p,false);assert.equal('token' in p,false);assert.throws(()=>profile({...p,port:0}));assert.throws(()=>profile({...p,host:'host;whoami'}));assert.throws(()=>name('../escape'));assert.throws(()=>safeDownloadName('CON.txt'));assert.throws(()=>safeDownloadName('a:b'));});
test('errors do not expose credential-bearing messages',()=>{const value=crypto.randomBytes(16).toString('hex');assert.ok(!publicError(new Error('password='+value)).includes(value));});
test('real SSH: probe has zero password attempts, changed key blocks before authentication, invalid password fails',async()=>{const f=await fixture(),s=new Server();try{assert.equal(await s.probe(f.profile),f.fingerprint);assert.equal(f.passwordAttempts,0);await assert.rejects(s.connect(f.profile,f.password,'SHA256:'+Buffer.alloc(32,7).toString('base64').replace(/=+$/,'')),e=>e.code==='HOST_KEY_CHANGED');assert.equal(f.passwordAttempts,0);await assert.rejects(s.connect(f.profile,'invalid-fixture-value',f.fingerprint));assert.equal(f.passwordAttempts,1);const result=await s.connect(f.profile,f.password,f.fingerprint);assert.ok(result.entries.some(e=>e.name==='hello.txt'));const stats=await s.stats();assert.match(stats.uptime,/up 2 days/);}finally{s.disconnect();await f.close();}});
function finish(q){if(!q.running)return Promise.resolve();return new Promise(resolve=>q.on('active',active=>{if(!active)resolve();}));}
test('real SFTP: streamed roundtrip, directory navigation, rename, delete, overwrite protection, cancellation',async()=>{const f=await fixture(),s=new Server(),local=fs.mkdtempSync(path.join(os.tmpdir(),'localls-local-'));try{await s.connect(f.profile,f.password,f.fingerprint);await call(s.sftp,'mkdir','/new');const dir=await s.list('/new');assert.equal(dir.path,'/new');const payload=crypto.randomBytes(2*1024*1024);const source=path.join(local,'source.bin');fs.writeFileSync(source,payload);const q=new Transfers(s);let runningObserved=false;q.on('update',items=>{if(items.some(j=>j.state==='running'))runningObserved=true;});q.add([{direction:'upload',local:source,remote:'/new/source.bin',label:'source.bin'}]);await finish(q);assert.equal(q.items[0].state,'completed');assert.deepEqual(fs.readFileSync(path.join(f.root,'new/source.bin')),payload);assert.ok(runningObserved);await call(s.sftp,'rename','/new/source.bin','/new/renamed.bin');const dest=path.join(local,'download.bin');q.add([{direction:'download',remote:'/new/renamed.bin',local:dest,label:'download.bin'}]);await finish(q);assert.equal(q.items[1].state,'completed');assert.deepEqual(fs.readFileSync(dest),payload);q.add([{direction:'download',remote:'/new/renamed.bin',local:dest,label:'existing'}]);await finish(q);assert.equal(q.items[2].state,'failed');assert.deepEqual(fs.readFileSync(dest),payload);q.add([{direction:'upload',local:source,remote:'/new/renamed.bin',label:'existing',overwrite:false}]);await finish(q);assert.equal(q.items[3].state,'failed');assert.deepEqual(fs.readFileSync(path.join(f.root,'new/renamed.bin')),payload);const ids=q.add([{direction:'download',remote:'/new/renamed.bin',local:path.join(local,'cancel.bin'),label:'cancel'},{direction:'download',remote:'/hello.txt',local:path.join(local,'after.txt'),label:'after'}]);q.cancel(ids[0]);await finish(q);assert.equal(q.items[4].state,'cancelled');assert.equal(q.items[5].state,'completed');assert.ok(!fs.existsSync(path.join(local,'cancel.bin')));assert.ok(!fs.readdirSync(local).some(n=>n.startsWith('.localls-')));assert.ok(!fs.readdirSync(path.join(f.root,'new')).some(n=>n.startsWith('.localls-')));await call(s.sftp,'unlink','/new/renamed.bin');await call(s.sftp,'rmdir','/new');assert.ok(!fs.existsSync(path.join(f.root,'new')));assert.ok(!JSON.stringify(q.snapshot()).includes(f.password));}finally{s.disconnect();await f.close();fs.rmSync(local,{recursive:true,force:true});}});
