'use strict';
const { _electron: electron }=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const {fixture}=require('../tests/fixture.cjs');
const wait=async(fn,timeout=30000)=>{const start=Date.now();for(;;){const result=await fn();if(result)return result;if(Date.now()-start>timeout)throw new Error('Timed out');await new Promise(resolve=>setTimeout(resolve,100));}};
(async()=>{const f=await fixture(),temp=fs.mkdtempSync(path.join(os.tmpdir(),'localls-ui-')),dataDir=path.join(temp,'user-data'),local=path.join(temp,'local');fs.mkdirSync(dataDir);fs.mkdirSync(local);fs.writeFileSync(path.join(local,'upload.bin'),crypto.randomBytes(8*1024*1024));const settings={profile:f.profile,pins:{},theme:'violet',shape:'rounded',route:'local',vpnHost:'',agentPort:8787,remember:false};fs.writeFileSync(path.join(dataDir,'settings.json'),JSON.stringify(settings));fs.writeFileSync(path.join(f.root,'<img onerror=alert(1)>.txt'),'unsafe-looking filename');let app;const errors=[],log=[];
try{
app=await electron.launch({args:['--no-sandbox','--disable-gpu','--user-data-dir='+dataDir,path.resolve('.')],env:{...process.env,DISPLAY:process.env.DISPLAY||':99',XDG_CONFIG_HOME:path.join(temp,'config'),XDG_CACHE_HOME:path.join(temp,'cache')},timeout:30000});
const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());log.push(msg.text());});
await app.evaluate(({dialog},paths)=>{dialog.showMessageBox=async(_window,options)=>({response:1});dialog.showOpenDialog=async(_window,options)=>({canceled:false,filePaths:options.properties.includes('openFile')?[paths.upload]:[paths.local]});},{local,upload:path.join(local,'upload.bin')});
await page.waitForFunction(()=>document.getElementById('hostMetric').textContent==='127.0.0.1');
assert.equal(await page.evaluate(()=>typeof window.require),'undefined');
await page.locator('[data-drawer="connection"]').first().click();await page.locator('#password').fill(f.password);await page.locator('#saveSettings').click();await page.locator('#saveStatus').filter({hasText:'Сохранено'}).waitFor();await page.locator('#closeDrawer').click();await page.locator('#connectButton').click();await page.waitForFunction(()=>document.getElementById('connectionBadge').textContent==='Подключено');assert.equal(f.passwordAttempts,1);console.log('PASS step: connection and host key');
await page.locator('#openFiles').click();await page.locator('#remoteEntries .file-row').filter({hasText:'hello.txt'}).waitFor();await page.locator('#remoteEntries .file-row').filter({hasText:'hello.txt'}).click();await page.locator('#remoteEntries .file-row').filter({hasText:'documents'}).dblclick();await page.waitForFunction(()=>document.getElementById('remotePath').value==='/documents');assert.match(await page.locator('#selectionCount').textContent(),/^1 на сервере/);await page.locator('#downloadFiles').click();await wait(()=>fs.existsSync(path.join(local,'hello.txt')));assert.equal(fs.readFileSync(path.join(local,'hello.txt'),'utf8'),'LocalLS real SFTP fixture\n');console.log('PASS step: real download and cross-folder selection');
await page.locator('#chooseLocal').click();await page.locator('#localEntries .file-row').filter({hasText:'upload.bin'}).waitFor();
await page.locator('#attachFiles').click();await page.locator('#attachmentBar').waitFor();console.log('PASS step: file attachment');await page.locator('#sendAttachments').click();await page.evaluate(()=>window.localLS.tray());assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),false);console.log('PASS step: hidden window / tray');await wait(async()=>{const s=await page.evaluate(()=>window.localLS.state());const j=s.data.transfers.find(j=>j.label==='upload.bin');if(j?.state==='failed')throw new Error('Upload failed: '+j.error);return j?.state==='completed';});console.log('PASS step: real background upload');assert.deepEqual(fs.readFileSync(path.join(f.root,'documents/upload.bin')),fs.readFileSync(path.join(local,'upload.bin')));await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].show());
await page.locator('#remoteUp').click();await page.locator('#remoteEntries .file-row').filter({hasText:'<img onerror=alert(1)>.txt'}).waitFor();assert.equal(await page.locator('#remoteEntries img').count(),0);
await page.locator('[data-drawer="settings"]').first().click();await page.locator('#theme').selectOption('dark');await page.locator('#shape').selectOption('circle');await page.locator('#saveSettings').click();await page.locator('#saveStatus').filter({hasText:'Сохранено'}).waitFor();assert.equal(await page.evaluate(()=>document.body.dataset.theme),'dark');await page.locator('#closeDrawer').click();
await page.locator('[data-drawer="vpn"]').first().click();await page.locator('#vpnStatus').filter({hasText:'Tailscale не установлен'}).waitFor();assert.equal(await page.locator('#vpnSwitch').isChecked(),false);await page.locator('#closeDrawer').click();
await page.locator('[data-page="overview"]').click();await page.locator('#refreshStats').click();await page.waitForFunction(()=>document.getElementById('uptime').textContent.includes('up 2 days'));await fs.promises.mkdir('artifacts/screenshots',{recursive:true});await page.screenshot({path:'artifacts/screenshots/LocalLS-dark.png'});
await page.locator('[data-drawer="settings"]').first().click();await page.locator('#theme').selectOption('violet');await page.locator('#shape').selectOption('rounded');await page.locator('#saveSettings').click();await page.locator('#closeDrawer').click();await page.screenshot({path:'artifacts/screenshots/LocalLS-overview.png'});await page.locator('[data-page="files"]').click();await page.screenshot({path:'artifacts/screenshots/LocalLS-files.png'});
await page.locator('#connectButton').click();await page.locator('[data-drawer="connection"]').first().click();await page.locator('#password').fill('invalid-fixture-value');await page.locator('#saveSettings').click();await page.locator('#closeDrawer').click();await page.locator('#connectButton').click();await page.locator('#toast').filter({hasText:'Сервер отклонил вход'}).waitFor();assert.equal(await page.locator('#connectionBadge').textContent(),'Не подключено');

await page.locator('[data-drawer="settings"]').first().click();await page.locator('[data-drawer="security"]').first().click();await page.locator('#generateIdentity').click();await page.locator('#identityStatus').filter({hasText:'Ключ готов'}).waitFor({timeout:60000});await page.locator('#keyBootstrapPassword').fill(f.password);await page.locator('#installIdentity').click();await page.waitForFunction(()=>document.getElementById('authMethod').value==='key',{},{timeout:60000});assert.equal(await page.locator('#password').isDisabled(),true);assert.equal(await page.locator('#keyBootstrapPassword').inputValue(),'');const secured=await page.evaluate(()=>window.localLS.state());assert.equal(secured.data.hasPassword,false);assert.equal(secured.data.identity.hasKey,true);assert.ok(!JSON.stringify(secured).includes('BEGIN RSA PRIVATE KEY'));assert.ok(!JSON.stringify(secured).includes('privateKey'));await page.locator('#closeDrawer').click();f.disablePasswords();const passwordsBefore=f.passwordAttempts;await page.locator('#connectButton').click();await page.waitForFunction(()=>document.getElementById('connectionBadge').textContent==='Подключено');assert.equal(f.passwordAttempts,passwordsBefore);assert.ok(f.publicKeyAttempts>0);console.log('PASS step: GUI key generation/enrollment, verified key-only login, no password fallback, no private key over IPC');await page.locator('#connectButton').click();const removed=await page.evaluate(()=>window.localLS.removeIdentity());assert.equal(removed.ok,true);assert.equal(removed.data.settings.authMethod,'key');assert.equal(removed.data.identity.hasKey,false);const failed=await page.evaluate(()=>window.localLS.connect());assert.equal(failed.ok,false);assert.equal(f.passwordAttempts,passwordsBefore);console.log('PASS step: missing local key fails closed without password fallback');

const persisted=fs.readFileSync(path.join(dataDir,'settings.json'),'utf8')+fs.readFileSync(path.join(dataDir,'history.json'),'utf8');assert.ok(!persisted.includes(f.password));assert.ok(!persisted.includes('BEGIN RSA PRIVATE KEY'));assert.ok(!persisted.includes('privateKey'));assert.ok(!persisted.includes('invalid-fixture-value'));assert.ok(!log.join('\n').includes(f.password));assert.deepEqual(errors,[]);const saved=JSON.parse(fs.readFileSync(path.join(dataDir,'settings.json'),'utf8'));assert.equal(saved.profile.port,f.profile.port);assert.equal(saved.profile.user,'fixture');assert.equal(saved.pins['127.0.0.1:'+f.profile.port],f.fingerprint);
await app.close();app=null;
app=await electron.launch({args:['--no-sandbox','--disable-gpu','--user-data-dir='+dataDir,path.resolve('.')],env:{...process.env,DISPLAY:process.env.DISPLAY||':99',XDG_CONFIG_HOME:path.join(temp,'config'),XDG_CACHE_HOME:path.join(temp,'cache')},timeout:30000});const next=await app.firstWindow();await next.waitForFunction(()=>document.getElementById('hostMetric').textContent==='127.0.0.1');const restored=await next.evaluate(()=>window.localLS.state());assert.equal(restored.data.hasPassword,false);assert.ok(restored.data.transfers.some(j=>j.state==='completed'));assert.equal(restored.data.settings.profile.port,f.profile.port);
console.log('PASS: actual Electron launch, isolated renderer, connection/key trust, real download/upload, cross-folder selection, tray/background transfer, appearance, VPN status, statistics, safe filename rendering, invalid password, no secrets in preferences/logs, restart/history persistence.');
}catch(e){if(app){const p=await app.firstWindow();console.log('Failure state:',await p.evaluate(async()=>{const s=await window.localLS.state();return JSON.stringify({notice:document.getElementById('toast').textContent,jobs:s.data?.transfers.map(j=>({label:j.label,state:j.state,error:j.error,bytes:j.bytes}))});}));await fs.promises.mkdir('artifacts/screenshots',{recursive:true});await p.screenshot({path:'artifacts/screenshots/ui-failure.png'});}throw e;}finally{await app?.close();await f.close();fs.rmSync(temp,{recursive:true,force:true});}
})().catch(e=>{console.error('UI smoke failed:',e.message);process.exitCode=1;});
