'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const assert=require('node:assert/strict');const asar=require('@electron/asar');
function hash(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function pe(file,machine){const b=fs.readFileSync(file);assert.equal(b.toString('ascii',0,2),'MZ');const offset=b.readUInt32LE(0x3c);assert.equal(b.readUInt32LE(offset),0x4550);assert.equal(b.readUInt16LE(offset+4),machine);assert.ok(b.length>1024*1024);return b;}
(async()=>{
const exe='artifacts/win-unpacked/LocalLS.exe',installer='artifacts/LocalLS-0.9.5-Windows-x64-Setup.exe',archive='artifacts/win-unpacked/resources/app.asar';
const PE=await import('pe-library'),R=await import('resedit');const b=pe(exe,0x8664);pe(installer,0x14c);const resources=PE.NtExecutableResource.from(PE.NtExecutable.from(b));const versions=R.Resource.VersionInfo.fromEntries(resources.entries);assert.ok(versions.some(v=>v.getStringValues({lang:1033,codepage:1200}).ProductName==='LocalLS'));const groups=R.Resource.IconGroupEntry.fromEntries(resources.entries);assert.ok(groups.length);const original=R.Data.IconFile.from(fs.readFileSync('assets/icon.ico'));assert.equal(groups[0].getIconItemsFromEntries(resources.entries).length,original.icons.length);
for(const relative of ['src/main.cjs','src/core.cjs','src/security.cjs','src/preload.cjs','src/index.html','src/style.css','src/renderer.js','assets/logo.svg','assets/icon.png'])assert.deepEqual(asar.extractFile(archive,relative),fs.readFileSync(relative),relative+' is stale');
const files=asar.listPackage(archive).map(file=>file.split(path.sep).join('/'));assert.ok(asar.extractFile(archive,'node_modules/ssh2/lib/client.js').length>1024);assert.ok(files.includes('/node_modules/ssh2/lib/client.js'));assert.ok(!files.some(f=>f.includes('fixture-credentials')||f.startsWith('/tools/')||f.startsWith('/tests/')||f.endsWith('vault.bin')));assert.ok(!files.some(f=>f.endsWith('.node')),'Windows package must not contain Linux native addons');const packaged=JSON.parse(asar.extractFile(archive,'package.json'));assert.equal(packaged.name,'localls-desktop');assert.equal(packaged.version,'0.9.5');
const manifest=fs.readFileSync('tools/uninstall-files.nsh','utf8');assert.ok(!manifest.includes('\\"'));assert.ok(!manifest.includes('RMDir /r'));assert.ok(manifest.includes('Delete "$INSTDIR\\LocalLS.exe"'));
const result={installer:{path:installer,size:fs.statSync(installer).size,sha256:hash(installer)},application:{path:exe,size:fs.statSync(exe).size,sha256:hash(exe)},archive:{path:archive,size:fs.statSync(archive).size,sha256:hash(archive)},package:'localls-desktop',version:'0.9.5',architecture:'Windows x64',appIcon:'cloud + lightning, 6 ICO sizes',sourceMatchesPackage:true,installerPE:true,uninstallerDeletesOnlyManifest:true,packagedFileCount:files.length};
fs.writeFileSync('artifacts/VERIFICATION.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e.message);process.exitCode=1;});
