'use strict';
const {app,BrowserWindow,ipcMain,dialog,Tray,Menu,nativeImage,safeStorage,shell,powerSaveBlocker} = require('electron');
const fs=require('node:fs'); const path=require('node:path'); const {execFile}=require('node:child_process');
const {profile,endpoint,name,remotePath,safeDownloadName,call,publicError,Server,Transfers}=require('./core.cjs');
const platform=require('./platform.cjs');
let localVerified=null, systemBusy=false;
const page=path.join(__dirname,'index.html'); const icon=path.join(__dirname,'../assets/icon.png');
let window, tray, quitting=false, blocker, settings, secretMemory={}, localRoot, attachments=new Set(), connecting=false;
const server=new Server(); const transfers=new Transfers(server);
const defaultSettings={profile:{host:'192.168.1.82',port:8022,user:'u0_a606',folder:'.',fingerprint:''},pins:{},theme:'violet',shape:'rounded',route:'local',vpnHost:'',agentPort:8787,remember:false};
if(app.commandLine.hasSwitch('user-data-dir'))app.setPath('userData',app.commandLine.getSwitchValue('user-data-dir'));
function authKey(p){return endpoint(p)+'@'+p.user;}
function file(n){return path.join(app.getPath('userData'),n);}
function read(n,fallback){try{return JSON.parse(fs.readFileSync(file(n),'utf8'));}catch{return fallback;}}
function write(n,v){fs.mkdirSync(app.getPath('userData'),{recursive:true});fs.writeFileSync(file(n),JSON.stringify(v,null,2),{mode:0o600});}
function vaultAvailable(){return safeStorage.isEncryptionAvailable() && (process.platform==='win32' || safeStorage.getSelectedStorageBackend()!=='basic_text');}
function secrets(){if(Object.keys(secretMemory).length)return secretMemory;try{if(vaultAvailable())secretMemory=JSON.parse(safeStorage.decryptString(fs.readFileSync(file('vault.bin'))));}catch{}return secretMemory;}
function saveSecrets(value){secretMemory=value;if(settings.remember&&vaultAvailable())fs.writeFileSync(file('vault.bin'),safeStorage.encryptString(JSON.stringify(value)),{mode:0o600});else fs.rmSync(file('vault.bin'),{force:true});}
function notify(type,data){if(window&&!window.isDestroyed())window.webContents.send('localls:'+type,data);}
function view(){return {settings,localRoot,connected:!!server.sftp,remotePath:server.location,vaultAvailable:vaultAvailable(),hasPassword:!!secrets()[authKey(effectiveProfile())]?.password,transfers:transfers.snapshot(),platform:process.platform};}
function effectiveProfile(){return profile({...settings.profile,host:settings.route==='vpn'?settings.vpnHost:settings.profile.host});}
async function confirm(message,detail=''){return (await dialog.showMessageBox(window,{type:'question',buttons:['Отмена','Продолжить'],defaultId:0,cancelId:0,message,detail})).response===1;}
function busy(){if(transfers.running)throw new Error('BUSY');}
function allowedLocal(p){const resolved=path.resolve(String(p));const rel=path.relative(localRoot,resolved);if(rel.startsWith('..'+path.sep)||rel==='..'||path.isAbsolute(rel))throw new Error('LOCAL_DENIED');const real=fs.realpathSync(resolved);const rr=path.relative(localRoot,real);if(rr==='..'||rr.startsWith('..'+path.sep)||path.isAbsolute(rr))throw new Error('LOCAL_DENIED');return real;}
async function localList(p){const folder=allowedLocal(p||localRoot);const entries=await fs.promises.readdir(folder,{withFileTypes:true});return {path:folder,root:localRoot,entries:await Promise.all(entries.map(async e=>{const full=path.join(folder,e.name);let st;try{st=await fs.promises.stat(full);}catch{}return {name:e.name,path:full,directory:e.isDirectory(),link:e.isSymbolicLink(),size:st?.size||0,modified:st?.mtimeMs||0};})).then(a=>a.sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name)))};}
function register(action,fn){ipcMain.handle('localls:'+action,async(event,arg)=>{if(event.sender!==window?.webContents||event.senderFrame?.url!==require('node:url').pathToFileURL(page).href)throw new Error('IPC_DENIED');try{return {ok:true,data:await fn(arg)};}catch(err){return {ok:false,error:({AUTH_CANCELLED:'Системное подтверждение отменено',FEDORA_REQUIRED:'Настройка сервера доступна на Fedora',HELPER_MISSING:'Нужен установленный RPM LocalLS с системным помощником',POLKIT_MISSING:'Не найден polkit; установите его средствами Fedora',SYSTEM_ACTION_FAILED:'Системная операция не выполнена. Проверьте разрешение администратора, состояние службы и интернет для установки пакетов.',SETTINGS_MISSING:'Откройте настройки Wi-Fi или учётной записи через меню Fedora',VERIFY_REQUIRED:'Сначала подтвердите реальный SSH-вход',LOCAL_ADDRESS_REQUIRED:'Выберите актуальный адрес этого компьютера',PASSWORD_REQUIRED:'Введите пароль учётной записи Fedora'}[err?.message]) || (err?.message==='BUSY'?'Дождитесь окончания передач или отмените их':publicError(err))};}});}
register('state',view);
register('saveSettings',async arg=>{busy();const previous=effectiveProfile();const p=profile(arg.profile);const theme=['violet','dark','ocean','forest','amber'].includes(arg.theme)?arg.theme:'violet';const shape=['rounded','square','circle'].includes(arg.shape)?arg.shape:'rounded';const route=arg.route==='vpn'?'vpn':'local';const vpnHost=String(arg.vpnHost||'').trim();if(vpnHost)profile({...p,host:vpnHost});const port=Number(arg.agentPort||8787);if(!Number.isInteger(port)||port<1||port>65535)throw new Error('INVALID_PORT');settings={...settings,profile:p,theme,shape,route,vpnHost,agentPort:port,remember:!!arg.remember&&vaultAvailable()};const next=effectiveProfile();if(endpoint(previous)!==endpoint(next)||previous.user!==next.user||previous.folder!==next.folder){server.disconnect();notify('connection',{connected:false});}const key=authKey(next);const values={...secrets()};if(typeof arg.password==='string'&&arg.password.length){if(arg.password.length>4096)throw new Error('PASSWORD_LONG');values[key]={...values[key],password:arg.password};}if(typeof arg.agentToken==='string'&&arg.agentToken.length){if(arg.agentToken.length>4096)throw new Error('TOKEN_LONG');values[key]={...values[key],agentToken:arg.agentToken};}saveSecrets(values);write('settings.json',settings);return view();});
register('connect',async()=>{busy();if(connecting)throw new Error('BUSY');connecting=true;try{const p=effectiveProfile();let pin=settings.pins[endpoint(p)];const observed=await server.probe(p);if(pin&&pin!==observed)throw Object.assign(new Error('CHANGED'),{code:'HOST_KEY_CHANGED'});if(!pin){if(!await confirm('Доверять этому SSH-серверу?',`${p.host}:${p.port}\n${observed}\nСверьте отпечаток с сервером по доверенному каналу.`))return {cancelled:true};pin=observed;settings.pins[endpoint(p)]=pin;write('settings.json',settings);}const password=secrets()[authKey(p)]?.password||'';const result=await server.connect(p,password,pin);notify('connection',{connected:true});return result;}finally{connecting=false;}});
register('disconnect',()=>{busy();server.disconnect();return true;});
register('remoteList',p=>server.list(remotePath(p)));
register('stats',()=>server.stats());
register('localList',p=>localList(p));
register('chooseLocal',async()=>{const r=await dialog.showOpenDialog(window,{properties:['openDirectory'],defaultPath:localRoot});if(r.canceled)return null;localRoot=fs.realpathSync(r.filePaths[0]);return localList(localRoot);});
register('chooseUpload',async()=>{const r=await dialog.showOpenDialog(window,{properties:['openFile','multiSelections']});if(r.canceled)return [];for(const p of r.filePaths)attachments.add(p);return r.filePaths.map(p=>({path:p,name:path.basename(p),size:fs.statSync(p).size}));});
register('download',async arg=>{const files=arg?.files;if(!Array.isArray(files)||!files.length||files.length>1000)throw new Error('BAD_FILES');server.requireSftp();const r=await dialog.showOpenDialog(window,{title:'Папка для скачивания',properties:['openDirectory','createDirectory'],defaultPath:localRoot});if(r.canceled)return [];const folder=fs.realpathSync(r.filePaths[0]);const reserved=new Set();const jobs=[];for(const v of files){const remote=remotePath(v);const base=safeDownloadName(path.posix.basename(remote));let final=path.join(folder,base),n=1;const ext=path.extname(base),stem=base.slice(0,base.length-ext.length);while(fs.existsSync(final)||reserved.has(final))final=path.join(folder,`${stem} (${n++})${ext}`);reserved.add(final);jobs.push({direction:'download',remote,local:final,label:base});}return transfers.add(jobs);});
register('upload',async arg=>{const files=arg?.files;if(!Array.isArray(files)||!files.length||files.length>1000)throw new Error('BAD_FILES');const folder=remotePath(arg.folder);const s=server.requireSftp();const jobs=[];for(const p of files){const local=attachments.has(p)?p:allowedLocal(p);const label=name(path.basename(local));const st=await fs.promises.stat(local);if(!st.isFile())throw new Error('FILES_ONLY');const remote=path.posix.join(folder,label);let overwrite=false;try{await call(s,'lstat',remote);overwrite=true;}catch(e){if(e.code!==2)throw e;}if(overwrite&&!await confirm('Заменить файл на сервере?',label))continue;jobs.push({direction:'upload',remote,local,label,overwrite});}return transfers.add(jobs);});
register('mkdir',async arg=>{await call(server.requireSftp(),'mkdir',path.posix.join(remotePath(arg.folder),name(arg.name)));return true;});
register('rename',async arg=>{busy();const old=remotePath(arg.path),target=path.posix.join(path.posix.dirname(old),name(arg.name));const s=server.requireSftp();try{await call(s,'lstat',target);throw new Error('EXISTS');}catch(e){if(e.code!==2)throw e;}if(!await confirm('Переименовать?',`${path.posix.basename(old)} → ${arg.name}`))return false;await call(s,'rename',old,target);return true;});
register('remove',async arg=>{busy();const p=remotePath(arg.path);const s=server.requireSftp();const st=await call(s,'lstat',p);if(!await confirm('Удалить с сервера?',path.posix.basename(p)+'\nПапки удаляются только пустыми.'))return false;await call(s,st.isDirectory()?'rmdir':'unlink',p);return true;});
register('cancel',id=>{transfers.cancel(id);return true;});
register('forgetKey',async()=>{busy();const p=effectiveProfile();if(!await confirm('Забыть ключ SSH?',`${p.host}:${p.port}\nПри следующем подключении потребуется сверить новый ключ.`))return false;server.disconnect();delete settings.pins[endpoint(p)];write('settings.json',settings);return true;});
register('importProfile',async()=>{busy();const r=await dialog.showOpenDialog(window,{filters:[{name:'Профиль LocalLS',extensions:['json']}]});if(r.canceled)return null;const f=r.filePaths[0];if(fs.statSync(f).size>64000)throw new Error('PROFILE_LARGE');const input=JSON.parse(fs.readFileSync(f,'utf8'));if(input.format!=='localls-server-v1')throw new Error('PROFILE_FORMAT');const p=profile(input);const old=settings.pins[endpoint(p)];if(old&&p.fingerprint&&old!==p.fingerprint)throw Object.assign(new Error('CHANGED'),{code:'HOST_KEY_CHANGED'});if(p.fingerprint&&!old){if(!await confirm('Доверять ключу из импортируемого профиля?',`${p.host}:${p.port}\n${p.fingerprint}\nИмпортируйте профиль только из доверенного источника.`))return null;settings.pins[endpoint(p)]=p.fingerprint;}server.disconnect();settings.profile=p;settings.route='local';write('settings.json',settings);return view();});
register('exportProfile',async()=>{const p=effectiveProfile();p.fingerprint=settings.pins[endpoint(p)]||'';const r=await dialog.showSaveDialog(window,{defaultPath:'LocalLS-server.json',filters:[{name:'Профиль LocalLS',extensions:['json']}]});if(r.canceled)return false;fs.writeFileSync(r.filePath,JSON.stringify(p,null,2));return true;});
register('agent',async action=>{if(!['status','start','stop','restart'].includes(action))throw new Error('DENIED');if(action!=='status'){busy();if(!await confirm({start:'Запустить SSH-службу?',stop:'Остановить SSH-службу?',restart:'Перезапустить SSH-службу?'}[action],'Используется существующий агент сервера. Его автозапуск не изменяется.'))return null;}const p=effectiveProfile(),token=secrets()[authKey(p)]?.agentToken;if(!token)throw new Error('NO_TOKEN');const host=p.host.includes(':')?`[${p.host}]`:p.host;const res=await fetch(`http://${host}:${settings.agentPort}/${action}`,{method:action==='status'?'GET':'POST',headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(10000),redirect:'error'});if(!res.ok)throw new Error('AGENT_FAILED');const data=await res.json();return {ok:!!data.ok,running:data.sshd==='running',message:action==='status'?'Статус получен':'Команда отправлена агенту'};});
register('vpnStatus',()=>platform.vpnStatus());
register('vpnToggle',async on=>{if(typeof on!=='boolean')throw new Error('BAD_ARG');if(!await confirm(on?'Подключить Tailscale?':'Отключить Tailscale?','Fedora запросит системное подтверждение администратора. Вход в аккаунт Tailscale выполняется отдельно.'))return false;return platform.privileged(on?'tailscale-up':'tailscale-down');});
register('openTailscale',async()=>{const auth=await platform.tailscaleAuthURL();await shell.openExternal(auth||'https://tailscale.com/download/linux');return true;});
register('systemSettings',section=>platform.openSettings(section));
register('localServerStatus',()=>platform.serverInfo());
register('localServerAction',async action=>{busy();if(systemBusy)throw new Error('BUSY');const labels={install:'Установить штатный OpenSSH-server через DNF?',start:'Запустить штатную SSH-службу этого ПК?',stop:'Остановить SSH-службу этого ПК?',restart:'Перезапустить SSH-службу этого ПК?',enable:'Включить автозапуск штатной SSH-службы?',disable:'Отключить автозапуск штатной SSH-службы?', 'firewall-open':'Разрешить входящий SSH (порт 22) в зоне firewalld по умолчанию?', 'firewall-close':'Убрать разрешение SSH (порт 22) из зоны firewalld по умолчанию?'};if(!Object.hasOwn(labels,action))throw new Error('INVALID_ACTION');if(!await confirm(labels[action],'Операция относится к этому компьютеру Fedora. Системное окно запросит права администратора. Конфигурация SSH, пользовательские пароли и ключи не заменяются. Правило firewalld сохраняется и действует в зоне по умолчанию.'))return false;systemBusy=true;localVerified=null;try{await platform.privileged(action);return await platform.serverInfo();}finally{systemBusy=false;}});
register('localServerCheck',async arg=>{busy();if(systemBusy)throw new Error('BUSY');localVerified=null;const info=await platform.serverInfo();const p=profile({host:'127.0.0.1',port:arg?.port,user:info.user,folder:info.folder});if(typeof arg?.password!=='string'||!arg.password.length||arg.password.length>4096)throw new Error('PASSWORD_REQUIRED');const check=new Server();systemBusy=true;try{const fingerprint=await check.probe(p);if(!await confirm('Проверить SSH-вход на этом компьютере?',p.user+'@127.0.0.1:'+p.port+'\n'+fingerprint))return {cancelled:true};await check.connect(p,arg.password,fingerprint);localVerified={...p,fingerprint};return {ok:true,fingerprint,user:p.user,port:p.port,folder:p.folder};}finally{check.disconnect();systemBusy=false;}});
register('localServerExport',async arg=>{if(!localVerified)throw new Error('VERIFY_REQUIRED');if(!platform.localAddresses().includes(arg?.host))throw new Error('LOCAL_ADDRESS_REQUIRED');const p=profile({...localVerified,host:arg.host});const r=await dialog.showSaveDialog(window,{defaultPath:'LocalLS-Fedora-server.json',filters:[{name:'Профиль LocalLS',extensions:['json']}]});if(r.canceled)return false;fs.writeFileSync(r.filePath,JSON.stringify(p,null,2));return true;});
register('tray',()=>{window.minimize();return true;});
register('quit',async()=>{if(transfers.running&&!await confirm('Прервать передачи и выйти?'))return false;quitting=true;for(const j of transfers.items)transfers.cancel(j.id);server.disconnect();app.quit();return true;});
transfers.on('update',data=>{notify('transfers',data);if(settings)write('history.json',data.filter(j=>['completed','cancelled','failed'].includes(j.state)).slice(-200));});
transfers.on('active',active=>{if(active&&!blocker)blocker=powerSaveBlocker.start('prevent-app-suspension');if(!active&&blocker){powerSaveBlocker.stop(blocker);blocker=null;}});
server.on('closed',()=>notify('connection',{connected:false}));
if(!app.requestSingleInstanceLock())app.quit();else{
app.on('second-instance',()=>{window?.show();window?.restore();window?.focus();});
app.whenReady().then(()=>{settings={...defaultSettings,...read('settings.json',{})};try{settings.profile=profile(settings.profile);effectiveProfile();}catch{settings={...defaultSettings};}localRoot=fs.realpathSync(fs.existsSync(app.getPath('downloads'))?app.getPath('downloads'):app.getPath('home'));transfers.items=read('history.json',[]).filter(j=>['completed','failed','cancelled'].includes(j.state)).slice(-200);
window=new BrowserWindow({width:1280,height:840,minWidth:960,minHeight:660,title:'LocalLS',icon,backgroundColor:'#f6f5fa',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',(e,url)=>{if(url!==require('node:url').pathToFileURL(page).href)e.preventDefault();});window.webContents.session.setPermissionRequestHandler((_,__,cb)=>cb(false));
window.loadFile(page);window.on('close',e=>{if(!quitting){e.preventDefault();window.minimize();}});
const image=nativeImage.createFromPath(icon);try{tray=new Tray(image.resize({width:24,height:24}));tray.setToolTip('LocalLS — SSH / SFTP');tray.setContextMenu(Menu.buildFromTemplate([{label:'Открыть LocalLS',click:()=>{window.show();window.focus();}},{type:'separator'},{label:'Выйти',click:async()=>{if(transfers.running&&!await confirm('Прервать передачи и выйти?'))return;quitting=true;for(const j of transfers.items)transfers.cancel(j.id);server.disconnect();app.quit();}}]));tray.on('click',()=>{window.show();window.restore();window.focus();});}catch{tray=null;}
});
app.on('window-all-closed',()=>{});app.on('before-quit',()=>{quitting=true;server.disconnect();});}
