'use strict';
const fs=require('node:fs');const os=require('node:os');const {execFile}=require('node:child_process');
const helper='/usr/libexec/localls-server-helper.py';
const actions=new Set(['install','start','stop','restart','enable','disable','firewall-open','firewall-close','tailscale-up','tailscale-down']);
function trustedProgram(paths){for(const p of paths){try{const s=fs.statSync(p);if(s.isFile()&&s.uid===0&&!(s.mode&0o022))return p;}catch{}}return null;}
function execute(command,args,timeout=30000){return new Promise((resolve,reject)=>{execFile(command,args,{timeout,maxBuffer:128*1024},(err,out)=>err?reject(new Error(err.code===126||err.code===127?'AUTH_CANCELLED':'SYSTEM_ACTION_FAILED')):resolve(out));});}
function isFedora(){try{return /^ID=(?:fedora|"fedora")$/m.test(fs.readFileSync('/etc/os-release','utf8'));}catch{return false;}}
function localAddresses(){return Object.values(os.networkInterfaces()).flat().filter(a=>a&&!a.internal&&a.family==='IPv4').map(a=>a.address);}
async function serverInfo(){let state='недоступен',enabled=false;try{state=(await execute('/usr/bin/systemctl',['is-active','sshd.service'])).trim();}catch{state='не запущен';}try{enabled=(await execute('/usr/bin/systemctl',['is-enabled','sshd.service'])).trim()==='enabled';}catch{}
 return {fedora:isFedora(),installed:!!trustedProgram(['/usr/sbin/sshd','/usr/bin/sshd']),running:state==='active',enabled,user:os.userInfo().username,folder:os.homedir(),addresses:localAddresses(),helperAvailable:!!trustedProgram([helper]),state};}
async function privileged(action){if(!actions.has(action))throw new Error('INVALID_ACTION');if(!isFedora())throw new Error('FEDORA_REQUIRED');if(!trustedProgram([helper]))throw new Error('HELPER_MISSING');const pkexec=trustedProgram(['/usr/bin/pkexec']),python=trustedProgram(['/usr/bin/python3']);if(!pkexec||!python)throw new Error('POLKIT_MISSING');let data;try{data=JSON.parse(await execute(pkexec,[python,'-I',helper,action],660000));}catch(e){throw new Error(e.message==='AUTH_CANCELLED'?'AUTH_CANCELLED':'SYSTEM_ACTION_FAILED');}if(!data.ok)throw new Error('SYSTEM_ACTION_FAILED');return true;}
function tailscalePath(){return trustedProgram(['/usr/bin/tailscale','/usr/local/bin/tailscale']);}
function validatedAuthURL(value){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='login.tailscale.com'&&!u.username&&!u.password&&u.pathname.startsWith('/a/')?u.href:null;}catch{return null;}}
async function tailscaleAuthURL(){const bin=tailscalePath();if(!bin)return null;try{const s=JSON.parse(await execute(bin,['status','--json']));return validatedAuthURL(s.AuthURL);}catch{return null;}}
async function vpnStatus(){const bin=tailscalePath();if(!bin)return {installed:false,running:false};try{const s=JSON.parse(await execute(bin,['status','--json']));return {installed:true,running:s.BackendState==='Running',state:String(s.BackendState||''),ip:s.TailscaleIPs?.[0]||''};}catch{return {installed:true,running:false,state:'Недоступен'};}}
async function openSettings(section){if(!['wifi','users'].includes(section))throw new Error('INVALID_ACTION');const gnome=trustedProgram(['/usr/bin/gnome-control-center']);if(gnome){execFile(gnome,[section==='wifi'?'wifi':'user-accounts'],()=>{});return true;}const kde=trustedProgram(['/usr/bin/systemsettings','/usr/bin/systemsettings5']);if(kde){execFile(kde,[section==='wifi'?'kcm_networkmanagement':'kcm_users'],()=>{});return true;}throw new Error('SETTINGS_MISSING');}
module.exports={actions,helper,trustedProgram,execute,isFedora,localAddresses,serverInfo,privileged,tailscalePath,vpnStatus,openSettings,validatedAuthURL,tailscaleAuthURL};
