'use strict';
const $=id=>document.getElementById(id), api=window.localLS;
const icons={dashboard:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',folder:'M3 7V5h6l2 2h10v13H3z',folderPlus:'M3 7V5h6l2 2h10v13H3z M12 11v6 M9 14h6',history:'M3 10a9 9 0 1 1 1 8 M3 4v6h6 M12 7v5l3 2',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6z M8 12l3 3 5-6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',plug:'M8 3v5 M16 3v5 M5 8h14v4a7 7 0 0 1-14 0z M12 19v3',server:'M4 3h16v7H4z M4 14h16v7H4z M7 7h1 M7 18h1 M11 7h6 M11 18h6',activity:'M2 12h5l3-9 4 18 3-9h5',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',upload:'M12 15V3 M7 8l5-5 5 5 M4 16v5h16v-5',restart:'M21 10a9 9 0 1 0-1 8 M21 4v6h-6',sliders:'M4 3v18 M12 3v18 M20 3v18 M1 8h6 M9 16h6 M17 7h6',refresh:'M21 10a9 9 0 0 0-15-6L3 7 M3 3v4h4 M3 14a9 9 0 0 0 15 6l3-3 M21 21v-4h-4',computer:'M3 3h18v13H3z M12 16v5 M7 21h10',up:'m6 14 6-6 6 6',arrow:'M3 12h18 M15 6l6 6-6 6',edit:'m4 16 12-12 4 4-12 12-5 1z M13 7l4 4',trash:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7',close:'M5 5l14 14 M19 5 5 19',file:'M5 3h9l5 5v13H5z M14 3v6h5',import:'M12 3v13 M7 11l5 5 5-5 M4 16v5h16v-5',export:'M12 16V3 M7 8l5-5 5 5 M4 16v5h16v-5',save:'M4 3h14l3 3v15H3V3z M7 3v6h10V3 M7 21v-8h10v8',play:'m8 4 13 8-13 8z',stop:'M5 5h14v14H5z',tray:'M4 4h16v16H4z M8 11l4 4 4-4 M12 6v9',check:'m5 12 4 4L19 6'};
function icon(kind){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','icon');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',icons[kind]||icons.file);svg.append(p);return svg;}
for(const el of document.querySelectorAll('[data-icon]'))el.prepend(icon(el.dataset.icon));
let state,connected=false,currentPage='overview',remoteFolder='.',localFolder='',localRoot='',pendingAttachments=[],jobs=[],toastTimer;
let remoteGeneration=0,localGeneration=0,connectionGeneration=0,statsRunning=false,connectRunning=false;
const remoteSelected=new Map(),localSelected=new Map(),speeds=Array(120).fill(0);let lastBytesSample=null,lastSampleAt=performance.now();
function bytes(n){n=Number(n)||0;if(n<1024)return Math.round(n)+' Б';if(n<1048576)return (n/1024).toFixed(1)+' КБ';if(n<1073741824)return (n/1048576).toFixed(1)+' МБ';return (n/1073741824).toFixed(2)+' ГБ';}
function toast(msg,error=false){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').classList.remove('hidden');$('toast').classList.toggle('error',error);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),error?7000:4000);}
async function invoke(action,arg){const r=await api[action](arg);if(!r.ok)throw new Error(r.error);return r.data;}
function on(id,fn){$(id).addEventListener('click',async()=>{try{await fn();}catch(e){toast(e.message,true);}});}
function setConnection(value){connected=value;connectionGeneration++;$('connectionBadge').textContent=value?'Подключено':'Не подключено';$('connectionBadge').classList.toggle('connected',value);$('connectButton').replaceChildren(icon('plug'),document.createTextNode(value?'Отключиться':'Подключиться'));$('footerState').replaceChildren(Object.assign(document.createElement('i'),{className:value?'connected':''}),document.createTextNode(value?'Подключение защищено SSH':'Готов к подключению'));$('sideDot').classList.toggle('connected',value);$('sideHost').textContent=value?(state.settings.route==='vpn'?state.settings.vpnHost:state.settings.profile.host):'Нет подключения';if(!value){remoteSelected.clear();selectionCount();remoteGeneration++;$('remoteEntries').replaceChildren();$('remoteEntries').classList.add('empty');$('remoteEntries').textContent='Подключитесь к серверу';$('pingMetric').textContent='—';$('uptime').textContent='Подключитесь для проверки';$('disk').textContent='—';}}
function applyState(value,fill=true){state=value;const s=value.settings;document.body.dataset.theme=s.theme;document.body.dataset.shape=s.shape;const p=s.profile;if(fill){for(const key of ['host','port','user','folder'])$(key).value=p[key];for(const key of ['theme','shape','route','vpnHost','agentPort'])$(key).value=s[key];$('password').value='';$('agentToken').value='';$('password').placeholder=value.hasPassword?'Сохранён · введите для замены':'Введите пароль';$('remember').checked=s.remember;$('remember').disabled=!value.vaultAvailable;$('vaultHint').textContent=value.vaultAvailable?'Секреты защищены системным шифрованием.':'Защищённое хранилище недоступно. Секреты останутся только в памяти.';}$('hostMetric').textContent=s.route==='vpn'?s.vpnHost||'Не задан':p.host;$('routeMetric').textContent=(s.route==='vpn'?'VPN / Tailscale':'Локальная сеть')+' · порт '+p.port;$('userMetric').textContent=p.user;}
function page(id){currentPage=id;for(const el of document.querySelectorAll('.page'))el.classList.toggle('hidden',el.id!==id);for(const el of document.querySelectorAll('[data-page]'))el.classList.toggle('active',el.dataset.page===id);$('pageTitle').textContent={overview:'Обзор сервера',files:'Файлы и папки',history:'Передачи'}[id];if(id==='files'){if(!localFolder)loadLocal(localRoot).catch(e=>toast(e.message,true));if(connected)loadRemote(remoteFolder).catch(e=>toast(e.message,true));}if(id==='overview')drawChart();}
for(const el of document.querySelectorAll('[data-page]'))el.addEventListener('click',()=>page(el.dataset.page));
function drawer(panel){$('drawer').classList.remove('hidden');$('drawerShade').classList.remove('hidden');$('drawerTitle').textContent={settings:'Настройки',connection:'Подключение',vpn:'VPN / Tailscale',server:'Управление сервером',localserver:'Этот компьютер — сервер'}[panel];for(const el of document.querySelectorAll('[data-panel]'))el.classList.toggle('hidden',el.dataset.panel!==panel);$('saveStatus').textContent='';if(panel==='localserver')refreshLocalServer().catch(e=>toast(e.message,true));if(panel==='vpn')checkVpn().catch(e=>toast(e.message,true));}
for(const el of document.querySelectorAll('[data-drawer]'))el.addEventListener('click',()=>drawer(el.dataset.drawer));
function closeDrawer(){$('drawer').classList.add('hidden');$('drawerShade').classList.add('hidden');document.body.dataset.theme=state.settings.theme;document.body.dataset.shape=state.settings.shape;drawChart();}
on('closeDrawer',closeDrawer);$('drawerShade').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();});
$('theme').addEventListener('change',()=>{document.body.dataset.theme=$('theme').value;drawChart();});$('shape').addEventListener('change',()=>document.body.dataset.shape=$('shape').value);
async function save(){const payload={profile:Object.fromEntries(['host','port','user','folder'].map(k=>[k,$(k).value])),...Object.fromEntries(['theme','shape','route','vpnHost','agentPort','password','agentToken'].map(k=>[k,$(k).value])),remember:$('remember').checked};const next=await invoke('saveSettings',payload);applyState(next);setConnection(next.connected);$('saveStatus').textContent='Сохранено';return next;}
on('saveSettings',save);
on('connectButton',async()=>{if(connectRunning)return;connectRunning=true;$('connectButton').disabled=true;try{if(connected){await invoke('disconnect');setConnection(false);}else{toast('Проверяем сервер и ключ SSH…');const result=await invoke('connect');if(result.cancelled)return;setConnection(true);remoteFolder=result.path;renderEntries('remote',result);await refreshStats();}}finally{connectRunning=false;$('connectButton').disabled=false;}});
on('openFiles',()=>page('files'));on('viewHistory',()=>page('history'));
function renderEntries(side,data){const box=$(side+'Entries');box.replaceChildren();box.classList.remove('empty');const selection=side==='remote'?remoteSelected:localSelected;for(const e of data.entries){const row=document.createElement('button');row.className='file-row';row.title=e.name;row.dataset.path=e.path;row.classList.toggle('selected',selection.has(e.path));if(!e.directory&&!e.link){const check=document.createElement('input');check.type='checkbox';check.checked=selection.has(e.path);check.tabIndex=-1;check.setAttribute('aria-label','Выбрать '+e.name);row.append(check);}else row.append(icon('folder'));row.append(icon(e.directory?'folder':'file'));const label=document.createElement('span');label.className='file-name';label.textContent=e.name;const size=document.createElement('span');size.className='size';size.textContent=e.directory?'Папка':bytes(e.size);row.append(label,size);row.addEventListener('click',()=>{if(e.directory||e.link)return;if(selection.has(e.path))selection.delete(e.path);else selection.set(e.path,e);row.classList.toggle('selected',selection.has(e.path));row.querySelector('input').checked=selection.has(e.path);selectionCount();});row.addEventListener('dblclick',()=>{if(e.directory){(side==='remote'?loadRemote(e.path):loadLocal(e.path)).catch(err=>toast(err.message,true));}});box.append(row);}if(!data.entries.length){box.classList.add('empty');box.textContent='Папка пуста';}$(side+'Path')[side==='remote'?'value':'textContent']=data.path;$(side+'Summary').textContent=data.entries.length+' элементов';if(side==='local')localFolder=data.path;else remoteFolder=data.path;selectionCount();}
async function loadRemote(folder){if(!connected)return;const generation=++remoteGeneration;const result=await invoke('remoteList',folder);if(generation===remoteGeneration&&connected)renderEntries('remote',result);}
async function loadLocal(folder){const generation=++localGeneration;const result=await invoke('localList',folder);if(generation===localGeneration)renderEntries('local',result);}
function parentRemote(p){const parts=p.split('/');parts.pop();return parts.join('/')||'/';}
function parentLocal(p){const n=p.replace(/[\\/]$/,'').lastIndexOf(state.platform==='win32'?'\\':'/');return p.slice(0,n)||localRoot;}
function selectionCount(){$('selectionCount').textContent=remoteSelected.size+' на сервере · '+localSelected.size+' на ПК';}
on('localUp',()=>{if(localFolder===localRoot)return;return loadLocal(parentLocal(localFolder));});on('remoteUp',()=>loadRemote(parentRemote(remoteFolder)));on('goRemote',()=>loadRemote($('remotePath').value));$('remotePath').addEventListener('keydown',e=>{if(e.key==='Enter')loadRemote(e.target.value).catch(err=>toast(err.message,true));});
on('chooseLocal',async()=>{const result=await invoke('chooseLocal');if(result){localRoot=result.root;localSelected.clear();renderEntries('local',result);}});
on('refreshFiles',async()=>{await Promise.all([loadLocal(localFolder||localRoot),loadRemote(remoteFolder)]);});
on('clearSelection',()=>{remoteSelected.clear();localSelected.clear();for(const row of document.querySelectorAll('.file-row.selected')){row.classList.remove('selected');if(row.querySelector('input'))row.querySelector('input').checked=false;}selectionCount();});
async function attach(){if(!connected){drawer('connection');toast('Сначала подключитесь к серверу');return;}page('files');if(localSelected.size){await invoke('upload',{files:[...localSelected.keys()],folder:remoteFolder});toast('Файлы добавлены в очередь');return;}pendingAttachments=await invoke('chooseUpload');$('attachmentBar').classList.toggle('hidden',!pendingAttachments.length);$('attachmentLabel').textContent=pendingAttachments.length+' вложений · '+bytes(pendingAttachments.reduce((n,f)=>n+f.size,0));}
on('attachOverview',attach);on('attachFiles',attach);on('discardAttachments',()=>{pendingAttachments=[];$('attachmentBar').classList.add('hidden');});on('sendAttachments',async()=>{await invoke('upload',{files:pendingAttachments.map(f=>f.path),folder:remoteFolder});pendingAttachments=[];$('attachmentBar').classList.add('hidden');toast('Файлы добавлены в очередь');});
on('downloadFiles',async()=>{if(!remoteSelected.size){toast('Выберите файлы на сервере');return;}const ids=await invoke('download',{files:[...remoteSelected.keys()]});if(ids.length)toast('Скачивание добавлено в очередь');});
async function askName(title,value=''){const dlg=$('nameDialog');$('nameTitle').textContent=title;$('nameInput').value=value;dlg.showModal();$('nameInput').focus();return new Promise(resolve=>dlg.addEventListener('close',()=>resolve(dlg.returnValue==='ok'?$('nameInput').value:null),{once:true}));}
on('newFolder',async()=>{if(!connected)return toast('Сначала подключитесь');const n=await askName('Новая папка');if(n){await invoke('mkdir',{folder:remoteFolder,name:n});await loadRemote(remoteFolder);}});
on('renameFile',async()=>{if(remoteSelected.size!==1)return toast('Выберите один файл');const [p,e]=[...remoteSelected.entries()][0];const n=await askName('Переименовать',e.name);if(n&&await invoke('rename',{path:p,name:n})){remoteSelected.delete(p);await loadRemote(remoteFolder);}});
on('deleteFile',async()=>{if(remoteSelected.size!==1)return toast('Выберите один файл');const p=[...remoteSelected.keys()][0];if(await invoke('remove',{path:p})){remoteSelected.delete(p);await loadRemote(remoteFolder);}});
async function refreshStats(){if(!connected)return toast('Сначала подключитесь');if(statsRunning)return;statsRunning=true;const generation=connectionGeneration,start=performance.now();try{const s=await invoke('stats');if(generation!==connectionGeneration||!connected)return;$('pingMetric').textContent=Math.round(performance.now()-start)+' мс';$('uptime').textContent=s.uptime;$('disk').textContent=s.disk;}finally{statsRunning=false;}}
on('refreshStats',refreshStats);
const labels={queued:'В очереди',running:'Передаётся',completed:'Готово',failed:'Ошибка',cancelled:'Отменено'};
function transferRow(j){const row=document.createElement('div');row.className='transfer';row.append(icon(j.direction==='upload'?'upload':'download'));const main=document.createElement('div');main.className='transfer-main';const title=document.createElement('span');title.className='transfer-title';title.textContent=j.label;const sub=document.createElement('small');sub.textContent=(j.direction==='upload'?'На сервер':'На компьютер')+' · '+bytes(j.bytes)+(j.total?' / '+bytes(j.total):'')+(j.error?' · '+j.error:'');main.append(title,sub);if(j.state==='running'){const bar=document.createElement('div');bar.className='progress';const fill=document.createElement('span');fill.style.width=(j.total?Math.min(100,j.bytes/j.total*100):0)+'%';bar.append(fill);main.append(bar);}row.append(main);const status=document.createElement('span');status.className='transfer-state';status.textContent=labels[j.state]||'—';row.append(status);if(['queued','running'].includes(j.state)){const cancel=document.createElement('button');cancel.className='icon-button';cancel.title='Отменить передачу';cancel.append(icon('close'));cancel.addEventListener('click',()=>invoke('cancel',j.id).catch(e=>toast(e.message,true)));row.append(cancel);}return row;}
function renderTransfers(data){jobs=data;$('queueBadge').textContent=jobs.filter(j=>['running','queued'].includes(j.state)).length;$('bytesMetric').textContent=bytes(jobs.reduce((n,j)=>n+j.bytes,0));$('completedMetric').textContent=jobs.filter(j=>j.state==='completed').length+' завершённых передач';for(const [id,items] of [['historyTransfers',[...jobs].reverse()],['recentTransfers',[...jobs].reverse().slice(0,3)]]){const el=$(id);el.replaceChildren();el.classList.toggle('empty',!items.length);if(!items.length)el.textContent='Пока нет передач';for(const j of items)el.append(transferRow(j));}}
function drawChart(){const canvas=$('speedChart'),rect=canvas.getBoundingClientRect();if(!rect.width)return;const ratio=window.devicePixelRatio||1;canvas.width=rect.width*ratio;canvas.height=149*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const w=rect.width,h=149,css=getComputedStyle(document.body),accent=css.getPropertyValue('--accent').trim(),line=css.getPropertyValue('--line').trim();const max=Math.max(1048576,...speeds);$('chartMax').textContent=bytes(max)+'/с';ctx.strokeStyle=line;ctx.lineWidth=1;for(let i=0;i<4;i++){const y=10+i*(h-20)/3;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}const gradient=ctx.createLinearGradient(0,0,0,h);gradient.addColorStop(0,accent+'38');gradient.addColorStop(1,accent+'00');const y=v=>h-10-v/max*(h-20);ctx.beginPath();ctx.moveTo(0,h-10);speeds.forEach((v,i)=>ctx.lineTo(i*w/(speeds.length-1),y(v)));ctx.lineTo(w,h-10);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();speeds.forEach((v,i)=>i?ctx.lineTo(i*w/(speeds.length-1),y(v)):ctx.moveTo(0,y(v)));ctx.strokeStyle=accent;ctx.lineWidth=2;ctx.stroke();}
setInterval(()=>{const now=performance.now(),total=jobs.reduce((n,j)=>n+j.bytes,0);const speed=lastBytesSample===null?0:Math.max(0,total-lastBytesSample)*1000/Math.max(1,now-lastSampleAt);lastBytesSample=total;lastSampleAt=now;speeds.shift();speeds.push(speed);$('speedLabel').textContent=bytes(speed)+'/с';$('footerSpeed').textContent='SFTP · '+bytes(speed)+'/с';if(currentPage==='overview')drawChart();},500);window.addEventListener('resize',drawChart);
async function checkVpn(){const s=await invoke('vpnStatus');$('vpnSwitch').checked=s.running;$('vpnStatus').textContent=s.installed?(s.running?'Подключён · '+s.ip:'Отключён · '+(s.state||'')):'Tailscale не установлен';}
on('checkVpn',checkVpn);on('openTailscale',()=>invoke('openTailscale'));$('vpnSwitch').addEventListener('change',async e=>{e.target.disabled=true;try{await invoke('vpnToggle',e.target.checked);await checkVpn();}catch(err){toast(err.message,true);await checkVpn();}finally{e.target.disabled=false;}});
async function agent(action){const result=await invoke('agent',action);if(result)toast(result.message+(action==='status'?(result.running?' · SSH работает':' · SSH остановлен'):''));}
for(const b of document.querySelectorAll('[data-agent]'))b.addEventListener('click',()=>agent(b.dataset.agent).catch(e=>toast(e.message,true)));on('restartServer',async()=>{try{await agent('restart');}catch{drawer('server');toast('Укажите порт и токен существующего агента, сохраните настройки и повторите команду',true);}});
on('hideToTray',()=>invoke('tray'));on('forgetKey',async()=>{if(await invoke('forgetKey')){setConnection(false);toast('Ключ удалён из доверенных');}});
on('importProfile',async()=>{const next=await invoke('importProfile');if(next){applyState(next);setConnection(false);remoteSelected.clear();toast('Профиль импортирован');}});on('exportProfile',async()=>{if(await invoke('exportProfile'))toast('Профиль сохранён без секретов');});
api.on('connection',s=>setConnection(s.connected));api.on('transfers',data=>{const previous=jobs;renderTransfers(data);if(data.some(j=>j.state==='completed'&&previous.find(o=>o.id===j.id)?.state!=='completed')){if(connected)loadRemote(remoteFolder).catch(()=>{});if(localFolder)loadLocal(localFolder).catch(()=>{});}});api.on('notice',n=>toast(n.message));
(async()=>{try{const initial=await invoke('state');applyState(initial);localRoot=initial.localRoot;remoteFolder=initial.remotePath;setConnection(initial.connected);renderTransfers(initial.transfers);lastBytesSample=initial.transfers.reduce((n,j)=>n+j.bytes,0);drawChart();}catch(e){toast(e.message,true);}})();

async function refreshLocalServer(){const info=await invoke('localServerStatus');$('localServerStatus').textContent=(info.fedora?'Fedora':'Настройка сервера поддерживается только на Fedora')+' · OpenSSH: '+(info.installed?'установлен':'не установлен')+' · SSH: '+(info.running?'работает':info.state)+' · автозапуск: '+(info.enabled?'включён':'выключен')+' · пользователь: '+info.user;const select=$('localServerHost'),old=select.value;select.replaceChildren();for(const address of info.addresses){const option=document.createElement('option');option.value=address;option.textContent=address;select.append(option);}if(info.addresses.includes(old))select.value=old;}
on('localServerRefresh',refreshLocalServer);on('openWifi',()=>invoke('systemSettings','wifi'));on('openUsers',()=>invoke('systemSettings','users'));on('quitApp',()=>invoke('quit'));
for(const button of document.querySelectorAll('[data-local-action]'))button.addEventListener('click',async()=>{const buttons=[...document.querySelectorAll('[data-local-action]')];buttons.forEach(b=>b.disabled=true);$('localServerExport').disabled=true;$('localServerPassword').value='';$('localServerResult').textContent='Ожидаем системное подтверждение и выполнение операции…';try{const result=await invoke('localServerAction',button.dataset.localAction);if(!result){$('localServerResult').textContent='Операция отменена';return;}$('localServerResult').textContent='Операция завершена. Проверьте статус и SSH-вход.';await refreshLocalServer();}catch(e){$('localServerResult').textContent=e.message;toast(e.message,true);}finally{buttons.forEach(b=>b.disabled=false);}});
on('localServerCheck',async()=>{const password=$('localServerPassword').value;$('localServerPassword').value='';$('localServerExport').disabled=true;const result=await invoke('localServerCheck',{port:Number($('localServerPort').value),password});if(result?.ok){$('localServerResult').textContent='SSH-вход подтверждён · '+result.fingerprint;$('localServerExport').disabled=false;}});
$('localServerPort').addEventListener('input',()=>{$('localServerExport').disabled=true;});on('localServerExport',async()=>{if(await invoke('localServerExport',{host:$('localServerHost').value}))toast('Профиль сохранён без пароля и токенов');});
